/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PipeWarpEventEnvelope = {
  [k: string]: unknown;
} & {
  schemaVersion: "0.1.0-alpha.0";
  id: string;
  type:
    | "run.created"
    | "run.queued"
    | "run.running"
    | "run.paused"
    | "run.succeeded"
    | "run.failed"
    | "run.canceled"
    | "task.created"
    | "task.queued"
    | "task.running"
    | "task.retrying"
    | "task.succeeded"
    | "task.failed";
  ts: string;
  source?: string;
  ctx: {
    flowId: string;
    runId: string;
    taskId?: string;
    taskInvocationId?: string;
  };
  payload?: unknown;
  artifacts?: Artifact[];
  metrics?: Metrics;
  trace?: Trace;
  errors?: Errors;
  [k: string]: unknown;
};
export type Errors = {
  code: string;
  message: string;
  details?: string;
}[];

export interface Artifact {
  name: string;
  uri: string;
  contentType: string;
  bytes?: number;
}
export interface Metrics {
  durationMs?: number;
  attempt?: number;
  cpuMs?: number;
  gpuMs?: number;
  peakMemBytes?: number;
}
export interface Trace {
  traceId?: string;
  spanId?: string;
}
