/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Task = ToolTask | TerminalTask;
export type NextRef =
  | string
  | {
      goto: string;
    };
export type NextRefOrPolicy =
  | NextRef
  | {
      policy: "half" | "retry";
      goto?: string;
      retries?: Retries;
    };

export interface PipeWarpFlowSpec {
  schemaVersion: "0.1.0-alpha.0";
  id: string;
  version: string;
  metadata?: {
    [k: string]: unknown;
  };
  entry: string;
  tasks: {
    [k: string]: Task;
  };
  /**
   * This interface was referenced by `PipeWarpFlowSpec`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]:
    | string
    | number
    | boolean
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | null;
}
export interface ToolTask {
  tool: string;
  type: string;
  inputs?: {
    [k: string]: unknown;
  };
  on: OnTransitions;
  retries?: Retries;
  metadata?: {
    [k: string]: unknown;
  };
}
export interface OnTransitions {
  success: NextRef;
  error: NextRefOrPolicy;
}
export interface Retries {
  max?: number;
  backoff?: "none" | "linear" | "exponential";
  baseMs?: number;
}
export interface TerminalTask {
  kind: "terminal";
  metadata?: {
    [k: string]: unknown;
  };
}
