/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Step = ToolStep;
export type NextRef =
  | string
  | {
      success?: string;
      failure?: string;
    };

export interface PipeWarpFlow {
  schemaVersion: "0.1.0-alpha.1";
  id: string;
  title?: string;
  description?: string;
  version: string;
  metadata?: {
    [k: string]: unknown;
  };
  start: string;
  steps: {
    [k: string]: Step;
  };
  [k: string]: unknown;
}
export interface ToolStep {
  type: "tool";
  mcp: string;
  tool: string;
  args?: {
    [k: string]: unknown;
  };
  save?: {
    [k: string]: unknown;
  };
  next?: NextRef;
  [k: string]: unknown;
}
