/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Pipewarp manifest file describing a tool.
 */
export interface PipeWarpToolManifest {
  schemaVersion: "0.1.0-alpha.0";
  name: string;
  /**
   * The SemVer of the tool.
   */
  version: string;
  /**
   * The kind of tool.
   */
  kind?: "stt" | "llm" | "tts" | "adapter" | "other";
  /**
   * Capabilities of the tool.
   */
  capabilities: {
    /**
     * List of IANA (MIME) media types the tool can accept as input.
     */
    mediaTypesIn?: string[];
    /**
     * List of IANA (MIME) media types the tool can produce as output.
     */
    mediaTypesOut?: string[];
  };
  limits?: {
    maxRuntimeMs?: number;
  };
  health: {
    /**
     * @minItems 1
     */
    endpoints: [HealthRedis, ...HealthRedis[]];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface HealthRedis {
  kind: "redis";
  /**
   * pw:tools:{name}:{instanceId}:hb
   */
  key: string;
  ttlSeconds: number;
  heartbeatIntervalMs: number;
}
